# GLOBAL CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────

    [solver]
        version = "v01"
#       Define maximum length for run-id. (e.g. 8 -> max. 10^8 runs)
        max_run_id_length = 8
    
    [file_io]
        path_to_config = "./config.toml"
        path_to_outfiles = "./out"
    
    [plotting]
        theme = "dark"
#       Possible values:
#       - "dark"
#       - "light"
        plot_which_runs = "last"
#       Possible values:
#       - "all"
#       - "last"
        plots_to_show = ["mass distribution", "mass error", "coagulation kernel"]  
#       Possible elements:
#       - "mass error"
#       - "mass distribution"
#       - "coagulation kernel"
        fig_size = [12, 8]
        steps_between_plot = 10

# SIMULATION CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────

    [mass_grid]
        mass_exponent_min = -5
        mass_exponent_max = +5
        mass_grid_resolution = 100
    
    [initialization]
        initial_mass_distribution = "dirac-delta" 
#       Possible values:
#       - "dirac-delta"
#       - "gaussian"
    
    [kernel]
        variant = "constant"
#       Possible values:
#       - "constant"
#       - "linear"
    
    [simulation]
        nr_of_timesteps = 100
